# Generated by Django 4.2.7 on 2023-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_addiabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addiabetes',
            name='image',
            field=models.ImageField(upload_to='images/diabetes'),
        ),
    ]
