# Generated by Django 4.2.7 on 2023-11-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addiabetes',
        ),
    ]
