# Generated by Django 4.2.7 on 2023-11-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_addiabetes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
