# Generated by Django 4.2.7 on 2023-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('a', 'Diabetescare'), ('b', 'Healthcare'), ('c', 'Painrelief'), ('d', 'Ayurveda'), ('e', 'Homeopathy'), ('f', 'Dermacare'), ('g', 'Oralcare'), ('h', 'Babycare'), ('i', 'Vitamins'), ('j', 'Sports'), ('k', 'Family'), ('l', 'Supports'), ('m', 'Weight')], default='a', max_length=100),
        ),
    ]
