# Generated by Django 4.2.7 on 2023-12-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_cart_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('delivered', models.BooleanField(default=False)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usersignup')),
            ],
        ),
    ]
