# Generated by Django 4.2.7 on 2023-12-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_mycart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
