# Generated by Django 4.2.7 on 2024-01-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_profile_delete_usrprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
